name: Pipeline CI/CD TD Master

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ci-cd-complet
  URL: ghcr.io

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v4

            - name: run tests
              run: ls -lah
    build:
        name: build
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build image
              run: docker build -t $IMAGE_NAME .
            - name: run image
              run: docker run -d -p 3000:3000 $IMAGE_NAME
            - name: tagger en version courante
              run: docker tag $IMAGE_NAME $URL/thomassanna/$IMAGE_NAME:1.0
            - name: tagger en version latest
              run: docker tag $IMAGE_NAME $URL/thomassanna/$IMAGE_NAME:latest
            - name: connexion à ghcr
              uses: docker/login-action@v2
              with:
                registry: ${{ env.URL }}
                username: thomassanna
                password: ${{ secrets.CICD_TOKEN }}
            - name: Push de l'image version 1.0
              run: docker push $URL/thomassanna/$IMAGE_NAME:1.0
            - name: Push de l'image version latest
              run: docker push $URL/thomassanna/$IMAGE_NAME:latest
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: connexion SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  IMAGE_NAME="${{ env.IMAGE_NAME }}"
                  IMAGE_URI="${{ env.URL }}/thomassanna/${{ env.IMAGE_NAME }}:latest"
                  echo "${{ secrets.CICD_TOKEN }}" | docker login "${{ env.URL }}" -u thomassanna --password-stdin
                  docker pull "$IMAGE_URI"
                  docker rm -f "$IMAGE_NAME" || true
                  docker run -d -p 3000:3000 --name "$IMAGE_NAME" "$IMAGE_URI"
                  sleep 5
                  curl --fail http://localhost:3000